// Systematic parity check between PennGammaSelector (C++) and
// AdaptivePolicy.select() (Python, eval_scene_distribution.py) -- the real
// version of what penn_gamma_diagnostic.cpp's single frozen state could
// only gesture at. Loads a batch of (pos, vel, goal, obstacles) states and
// their Python-computed expected gamma from cpp_parity_states.pt
// (generated by penn_gat_training/diag_gen_cpp_parity_states.py), runs
// each through this node's own selectGamma(), and reports agreement.
//
// A mismatch here means the offline validation (+24.3% out-of-sample,
// 0/350 hard collisions) describes a policy the vehicle does not actually
// run -- this is the assertion the redesign plan called for in place of a
// code review.
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

#include <torch/csrc/jit/serialization/pickle.h>
#include <torch/torch.h>

#include "single_vehicle_cbf_rate/penn_gamma_selector.hpp"

using nodelib::PennGammaSelector;

// 64-bit FNV-1a over a file's bytes. Mirrors diag_gen_cpp_parity_states.py's
// fnv1a64(). Not cryptographic -- a cheap cross-language content stamp so
// this check refuses to run against a checkpoint the fixture was not
// generated from (the silent Tier 1 failure found 2026-08-29).
static uint64_t fnv1a64File(const std::string& path) {
  std::ifstream f(path, std::ios::binary);
  if (!f) return 0;
  uint64_t h = 0xCBF29CE484222325ULL;
  char buf[1 << 16];
  while (f) {
    f.read(buf, sizeof(buf));
    const std::streamsize n = f.gcount();
    for (std::streamsize i = 0; i < n; ++i) {
      h ^= static_cast<uint8_t>(buf[i]);
      h *= 0x100000001B3ULL;
    }
  }
  return h;
}

// Resolve default asset paths from $ARC_ROOT (exported by scripts/setup.sh);
// fall back to a repo-root-relative path. Overridable via argv.
static std::string arcPath(const char* rel) {
  const char* root = std::getenv("ARC_ROOT");
  return (root && *root ? std::string(root) + "/" : std::string()) + rel;
}

int main(int argc, char** argv) {
  const std::string weights_path =
      argc > 1 ? argv[1]
                : arcPath("src/arc/single_vehicle_cbf_rate_arc/"
                          "nn_model/checkpoint/gat_penn_weights.pt");
  const std::string states_path =
      argc > 2 ? argv[2]
                : arcPath("src/arc/single_vehicle_cbf_rate_arc/"
                          "nn_model/checkpoint/cpp_parity_states.pt");

  PennGammaSelector selector(weights_path.c_str());

  std::ifstream file(states_path, std::ios::binary);
  if (!file) {
    std::fprintf(stderr, "cannot open %s\n", states_path.c_str());
    return 1;
  }
  std::vector<char> data((std::istreambuf_iterator<char>(file)), std::istreambuf_iterator<char>());
  const torch::IValue loaded = torch::jit::pickle_load(data);
  const auto dict = loaded.toGenericDict();

  // Staleness guard: refuse to run if the fixture was not generated from
  // the checkpoint we are about to check. A stale fixture turns Tier 1
  // from a guard into a wall of spurious mismatches (263/300 on
  // 2026-08-29) that reads as a real regression.
  if (dict.contains("weights_fnv1a64")) {
    const std::string want = dict.at("weights_fnv1a64").toStringRef();
    char got_buf[24];
    std::snprintf(got_buf, sizeof(got_buf), "0x%016llx",
                  static_cast<unsigned long long>(fnv1a64File(weights_path)));
    if (want != got_buf) {
      std::fprintf(stderr,
          "FATAL: parity fixture is stale.\n"
          "  fixture %s\n"
          "  was generated for a checkpoint with fnv1a64 = %s\n"
          "  but %s\n"
          "  hashes to %s.\n"
          "Regenerate: cd penn_gat_training && CHECKPOINT_NAME=<name> "
          "DEPLOY_GAMMA_MIN=<lo> DEPLOY_GAMMA_MAX=<hi> LCB_K=<k> "
          "python3 diag_gen_cpp_parity_states.py\n",
          states_path.c_str(), want.c_str(), weights_path.c_str(), got_buf);
      return 2;
    }
  } else {
    std::fprintf(stderr,
        "WARNING: parity fixture predates the staleness stamp (no "
        "weights_fnv1a64 key). Regenerate it to enable the guard.\n");
  }

  const int64_t n_states = dict.at("n_states").toInt();
  const int64_t max_obs = dict.at("max_obs").toInt();
  const torch::Tensor pos_t = dict.at("pos").toTensor();
  const torch::Tensor vel_t = dict.at("vel").toTensor();
  const torch::Tensor goal_t = dict.at("goal").toTensor();
  const torch::Tensor obs_centers_t = dict.at("obs_centers").toTensor();
  const torch::Tensor obs_radii_t = dict.at("obs_radii").toTensor();
  const torch::Tensor expected_t = dict.at("expected_gamma").toTensor();
  // prev_gamma: per-state input to the conservative fallback ratchet
  // (added 2026-08-29, PLAN_adaptive_hardening §0.4). Older fixtures lack
  // it -- fall back to gamma_max so the ratchet term is well-defined.
  const bool has_prev = dict.contains("prev_gamma");
  const torch::Tensor prev_gamma_t =
      has_prev ? dict.at("prev_gamma").toTensor() : torch::Tensor();

  PennGammaSelector::GammaSelectionParams params;
  params.gamma_min = dict.at("gamma_min").toDouble();
  params.gamma_max_candidate = dict.at("gamma_max_candidate").toDouble();
  params.gamma_steps = static_cast<int>(dict.at("gamma_steps").toInt());
  params.epistemic_threshold = dict.at("epistemic_threshold").toDouble();
  params.cvar_boundary = dict.at("cvar_boundary").toDouble();
  params.lcb_k = dict.contains("lcb_k") ? dict.at("lcb_k").toDouble() : 0.0;
  params.fallback_step = dict.contains("fallback_step") ? dict.at("fallback_step").toDouble() : 0.5;
  params.deadlock_threshold = 1.0e9;  // vestigial, never gates -- see selectGamma's comment

  const auto pos_acc = pos_t.accessor<float, 2>();
  const auto vel_acc = vel_t.accessor<float, 2>();
  const auto goal_acc = goal_t.accessor<float, 2>();
  const auto obs_c_acc = obs_centers_t.accessor<float, 3>();
  const auto obs_r_acc = obs_radii_t.accessor<float, 2>();
  const auto expected_acc = expected_t.accessor<float, 1>();
  const float* prev_gamma_acc = has_prev ? prev_gamma_t.data_ptr<float>() : nullptr;

  int n_pass = 0, n_fail = 0, n_nullopt = 0;
  double max_abs_err = 0.0;
  double sum_abs_err = 0.0;
  const double kTolerance = 0.02;  // < one candidate step ((gamma_max-gamma_min)/(steps-1)); see fixture

  for (int64_t i = 0; i < n_states; ++i) {
    const Eigen::Vector3d pos(pos_acc[i][0], pos_acc[i][1], pos_acc[i][2]);
    const Eigen::Vector3d vel(vel_acc[i][0], vel_acc[i][1], vel_acc[i][2]);
    const Eigen::Vector3d goal(goal_acc[i][0], goal_acc[i][1], goal_acc[i][2]);
    params.goal = goal;
    params.prev_gamma = prev_gamma_acc ? prev_gamma_acc[i] : params.gamma_max_candidate;

    std::vector<PennGammaSelector::ObstacleInput> obstacles;
    for (int64_t k = 0; k < max_obs; ++k) {
      const double r = obs_r_acc[i][k];
      if (r < 0.0) continue;  // padding sentinel
      obstacles.push_back({Eigen::Vector3d(obs_c_acc[i][k][0], obs_c_acc[i][k][1], obs_c_acc[i][k][2]), r});
    }

    const auto result = selector.selectGamma(pos, vel, obstacles, params);
    const double expected = expected_acc[i];

    if (!result.has_value()) {
      ++n_nullopt;
      std::printf("[%3lld] NULLOPT (C++ inference exception) -- Python expected %.4f\n",
                  static_cast<long long>(i), expected);
      continue;
    }

    const double err = std::abs(*result - expected);
    sum_abs_err += err;
    if (err > max_abs_err) max_abs_err = err;
    if (err <= kTolerance) {
      ++n_pass;
    } else {
      ++n_fail;
      std::printf("[%3lld] MISMATCH: cpp=%.4f  python=%.4f  |err|=%.4f  n_obs=%zu\n",
                  static_cast<long long>(i), *result, expected, err, obstacles.size());
      // Dump the full per-candidate table for mismatches -- distinguishes
      // a genuine structural bug (wildly different values) from a
      // near-tie decided differently by float32 accumulation order
      // (values close together, argmin unstable under tiny perturbation).
      const auto table = selector.diagnoseGammaSelection(pos, vel, obstacles, params);
      if (table.has_value()) {
        std::printf("       %8s %10s %10s %10s\n", "gamma", "div", "deadlock", "risk");
        for (const auto& row : *table) {
          std::printf("       %8.3f %10.5f %10.4f %10.4f\n", row.gamma, row.divergence,
                      row.mean_deadlock, row.mean_risk);
        }
      }
      if (std::getenv("DUMP_ZIJ") != nullptr) {
        const std::vector<float> zij = selector.debugZij(pos, vel, obstacles, goal);
        std::printf("ZIJ n_obs=%zu num_edges=%zu\n", obstacles.size(), zij.size() / 21);
        for (size_t r = 0; r < zij.size() / 21; ++r) {
          std::printf("row %zu:", r);
          for (int c = 0; c < 21; ++c) std::printf(" %.6f", zij[r * 21 + c]);
          std::printf("\n");
        }
        const std::vector<float> emb = selector.debugRobotEmb(pos, vel, obstacles, goal);
        std::printf("ROBOT_EMB:");
        for (float v : emb) std::printf(" %.6f", v);
        std::printf("\n");
      }
    }
  }

  std::printf("\n%d/%lld within tolerance (%.3f)  %d mismatches  %d nullopt\n", n_pass,
              static_cast<long long>(n_states), kTolerance, n_fail, n_nullopt);
  std::printf("mean |err| = %.5f   max |err| = %.5f\n", sum_abs_err / n_states, max_abs_err);

  return (n_fail == 0 && n_nullopt == 0) ? 0 : 1;
}
