#!/usr/bin/env bash
# Run once per machine. Detects the device, materialises .arc-local.env at the
# repo root (gitignored), and prepares the VS Code settings from the template.
#
#   scripts/setup.sh [device]
#
# Pass a device name to override hostname detection (desktop|laptop|jetson).
set -euo pipefail

ARC_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ARC_ROOT"

device="${1:-}"
if [ -z "$device" ]; then
  h="$(hostname)"
  case "$h" in
    *jetson*|*orin*|*tegra*) device=jetson ;;
    *laptop*|*book*)         device=laptop ;;
    *)                       device=desktop ;;
  esac
  echo "setup: hostname '$h' -> device '$device' (override: scripts/setup.sh <device>)"
fi

src="config/devices/${device}.env"
[ -f "$src" ] || { echo "setup: no such device file: $src" >&2; exit 1; }

{
  echo "# Generated by scripts/setup.sh on $(date -Iseconds) for '$device'."
  echo "# Gitignored. Edit freely — this is the per-machine config."
  echo "export ARC_ROOT=\"$ARC_ROOT\""
  cat "$src"
} > .arc-local.env
echo "setup: wrote .arc-local.env"

if [ ! -e .vscode/settings.json ] && [ -e .vscode/settings.json.template ]; then
  cp .vscode/settings.json.template .vscode/settings.json
  echo "setup: created .vscode/settings.json from template"
fi

# Keep colcon out of the local-only reference tree if it exists.
[ -d reference ] && touch reference/COLCON_IGNORE

echo "setup: done. 'source .arc-local.env' or use scripts/build.sh."
